name: Create Nifty 50 Database

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions UI

jobs:
  create_database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas pytz

      - name: Run database creation script
        run: python create_nifty50_db.py

      - name: Push database to GitHub
        run: |
          git config --global user.name "chiragpalan"
          git config --global user.email "your-email@example.com"
          git add nifty50_data.db
          git commit -m "Initialize Nifty 50 database"
          git push
