name: Download and Append CSVs to DB


on:
  schedule:
    # Run every 15 minutes Monday to Friday between 9:15 AM to 3:30 PM
    - cron: "15,30,45,00 9-15 * * 1-5"
  workflow_dispatch: # Allow manual trigger

jobs:
  download_and_commit_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true # Allow pushing changes to the repo
          fetch-depth: 0            # Ensure full history is fetched

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance=="0.2.30" pandas

      - name: Download Stock Data
        run: python create_and_save_temp_csv.py

      - name: Commit and Push CSV Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "chiragpalan"
          git config --global user.email "your-email@example.com"
          git add temp_csvs/*
          git commit -m "Update CSV files with new stock data"
          git push

  append_to_db:
    runs-on: ubuntu-latest
    needs: download_and_commit_csv
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance=="0.2.30"

      - name: Append Data to Database
        run: python append_database_with_temp_csv.py
