name: Download and Append CSVs to DB

on:
  schedule:
    # Run every 15 minutes Monday to Friday between 9:15 AM to 3:30 PM
    - cron: "15,30,45,00 9-15 * * 1-5"
  workflow_dispatch: # Allow manual trigger

jobs:
  download_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance==0.2.30 pandas

      - name: Download Stock Data
        run: |
          python create_and_save_temp_csv.py

  append_to_db:
    runs-on: ubuntu-latest
    needs: download_csv
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance=="0.2.30"

      - name: Append Data to Database
        run: |
          python append_database_with_temp_csv.py

