name: Download and Append CSVs to DB

on:
  schedule:
    # Run every 15 minutes Monday to Friday between 9:15 AM to 3:30 PM with a 2-minute delay between jobs
    - cron: '15,30,45,00 9-15 * * 1-5'  # This will run at 9:15, 9:30, 9:45, ..., 3:30 PM (Monday to Friday)
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  download_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance=="0.2.30" pandas

      - name: Download stock data and create CSV files
        run: |
          python create_and_save_temp_csv.py

  append_to_db:
    runs-on: ubuntu-latest
    needs: download_data
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Append data to the database
        run: |
          python append_database_with_temp_csv.py
