name: Download and Append CSVs to DB

on:
  schedule:
    - cron: '15,30,45,00 9-15 * * 1-5' 
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  download_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas

      - name: Run script to create CSVs
        run: |
          python create_and_save_temp_csv.py

      - name: Verify contents of temp_csvs
        run: |
          ls -la temp_csvs
          cat temp_csvs/*.csv || echo "No CSV files created."

      - name: Upload CSV files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: csv-files
          path: temp_csvs

  append_to_db:
    runs-on: ubuntu-latest
    needs: download_data
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download CSV files artifact
        uses: actions/download-artifact@v3
        with:
          name: csv-files

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run script to append data to the database
        run: |
          python append_database_with_temp_csv.py
