name: Fetch Stock Data Data

on:
  schedule:
    - cron: "*/15 3-10 * * 1-5"  # Every 15 minutes between 9:15 AM to 3:30 PM IST (adjusted to UTC)
  workflow_dispatch:

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance=="0.2.30" pandas pytz

      - name: Run script
        run: |
          python fetch_stock_data.py

      - name: Commit and push the database file if there are changes
        run: |
          git config --global user.name "chiragpalan"
          git config --global user.email "your-email@example.com"
          git add nifty50_data.db
          git commit -m "Update Nifty 50 data" || echo "No changes to commit."
          git push
